package com.example.microservicio_informacion_centro_medico.repository;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;

import com.example.microservicio_informacion_centro_medico.model.ProcedimientoEntity;
import com.example.microservicio_informacion_centro_medico.model.RequisitoEntity;
import com.example.microservicio_informacion_centro_medico.model.PasoEntity;
import com.example.microservicio_informacion_centro_medico.model.ProcedimientoElementoEntity;
import com.example.microservicio_informacion_centro_medico.model.ProcedimientoElementoPasoEntity;
import com.example.microservicio_informacion_centro_medico.model.ProcedimientoElementoRequisitoEntity;
import com.example.microservicio_informacion_centro_medico.model.util.ids_embebidos.ProcedimientoElementoRequisitoId;

public interface ProcedimientosElementosRequisitosRepositoryJPA extends JpaRepository<ProcedimientoElementoRequisitoEntity, Integer> {
    List<ProcedimientoElementoRequisitoEntity> findByProcedimientoElemento(ProcedimientoElementoEntity procedimientoElemento);
    Optional<ProcedimientoElementoRequisitoEntity> findOneByProcedimientoElementoAndRequisito(ProcedimientoElementoEntity procedimientoElemento,RequisitoEntity requisitoEntity);
}